sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t joo1004/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true joo1004/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucet_name: "elasticbeanstalk-ap-northeast-2-545782110066"
  buket_path: "docker-react-app"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_ACCESS_KEY
